"""
================================================================================
  flood_detection/gee_flood.py
  Google Earth Engine — Sentinel-1 SAR Flood Detection
================================================================================

  USAGE (requires authenticated GEE Python API):
  -----------------------------------------------
    import ee
    from flood_detection.gee_flood import GEEFloodDetector
    ee.Initialize()

    detector = GEEFloodDetector(
        roi_coords=[73.0, 18.0, 74.5, 19.5],   # [west, south, east, north]
        start_date="2024-07-01",
        end_date="2024-07-31"
    )
    flood_image = detector.run()
    detector.export_to_drive(flood_image, "flood_map_july2024")

================================================================================
"""

# ── NOTE: Uncomment imports when running with real GEE credentials ──────────
# import ee

import json
import logging

logger = logging.getLogger(__name__)


class GEEFloodDetector:
    """
    Google Earth Engine based Sentinel-1 SAR Flood Detector.

    Wraps the complete GEE processing chain:
      1. Load Sentinel-1 GRD collection
      2. Filter by date, region, polarization
      3. Apply edge & thermal noise removal (available in GEE)
      4. Compute median composite
      5. Threshold-based flood classification
      6. Export result

    Parameters
    ----------
    roi_coords : list of float
        Bounding box [west, south, east, north] in decimal degrees.
    start_date : str
        Start date string "YYYY-MM-DD".
    end_date : str
        End date string "YYYY-MM-DD".
    threshold_db : float
        VV backscatter threshold in dB. Default -16.0.
    polarization : str
        "VV", "VH", or "VV+VH". Default "VV".
    """

    # GEE collection ID for Sentinel-1 GRD products
    S1_COLLECTION = "COPERNICUS/S1_GRD"

    # JRC Global Surface Water — used to mask permanent water bodies
    JRC_WATER = "JRC/GSW1_4/GlobalSurfaceWater"

    def __init__(
        self,
        roi_coords: list,
        start_date: str,
        end_date: str,
        threshold_db: float = -16.0,
        polarization: str = "VV"
    ):
        self.roi_coords   = roi_coords
        self.start_date   = start_date
        self.end_date     = end_date
        self.threshold_db = threshold_db
        self.polarization = polarization.upper()

    # ──────────────────────────────────────────────────────────────────────────
    def build_gee_script(self) -> str:
        """
        Return the equivalent GEE JavaScript code as a string.
        Useful for running in the GEE Code Editor (code.earthengine.google.com).
        """
        script = f"""
// ============================================================
//  Sentinel-1 SAR Flood Detection — GEE Script
//  Auto-generated by GeoTwin Phase 1
// ============================================================

// 1. Define Region of Interest (ROI)
var roi = ee.Geometry.Rectangle([{", ".join(map(str, self.roi_coords))}]);

// 2. Load Sentinel-1 GRD collection
var s1 = ee.ImageCollection('{self.S1_COLLECTION}')
    .filterBounds(roi)
    .filterDate('{self.start_date}', '{self.end_date}')
    .filter(ee.Filter.eq('instrumentMode', 'IW'))          // Interferometric Wide swath
    .filter(ee.Filter.listContains('transmitterReceiverPolarisation', '{self.polarization}'))
    .filter(ee.Filter.eq('orbitProperties_pass', 'DESCENDING'))
    .select('{self.polarization}');

print('Sentinel-1 Images found:', s1.size());

// 3. Compute median composite (reduces speckle through temporal averaging)
var s1_median = s1.median().clip(roi);

// 4. Apply Focal Mean (Lee-like smoothing) for speckle reduction
var s1_smooth = s1_median.focal_mean({{
    radius: 30,
    kernelType: 'circle',
    units: 'meters'
}});

// 5. Flood classification by thresholding
var flood_mask = s1_smooth.lt({self.threshold_db});

// 6. Load JRC permanent water mask and exclude permanent water bodies
var jrc = ee.Image('{self.JRC_WATER}').select('seasonality');
var permanent_water = jrc.gte(10);   // Pixels with water ≥ 10 months/year
var flood_only = flood_mask.where(permanent_water, 0);

// 7. Morphological cleaning — remove isolated small patches
var flood_cleaned = flood_only
    .focal_min({{radius:1, kernelType:'square', units:'pixels'}})
    .focal_max({{radius:1, kernelType:'square', units:'pixels'}});

// 8. Visualization
var vis_params = {{
    min: 0, max: 1,
    palette: ['ffffff', '1e40af']   // white=dry, blue=flooded
}};
Map.centerObject(roi, 10);
Map.addLayer(s1_median,   {{min:-25, max:0, palette:['000000','ffffff']}}, 'SAR VV (dB)');
Map.addLayer(flood_cleaned, vis_params, 'Flood Mask');

// 9. Compute area statistics
var flood_area = flood_cleaned
    .multiply(ee.Image.pixelArea())
    .reduceRegion({{
        reducer: ee.Reducer.sum(),
        geometry: roi,
        scale: 10,
        maxPixels: 1e10
    }});

print('Flooded Area (m²):', flood_area);

// 10. Export to Google Drive
Export.image.toDrive({{
    image: flood_cleaned.toByte(),
    description: 'flood_map_{self.start_date.replace("-","")}_{self.end_date.replace("-","")}',
    folder: 'GeoTwin_Outputs',
    fileNamePrefix: 'flood_sentinel1',
    region: roi,
    scale: 10,
    crs: 'EPSG:4326',
    maxPixels: 1e10
}});
"""
        return script

    # ──────────────────────────────────────────────────────────────────────────
    def run_python_api(self):
        """
        Execute flood detection using the GEE Python API.
        Requires: `import ee; ee.Initialize()` called before this method.

        Returns
        -------
        ee.Image
            Binary flood classification image (0=dry, 1=flooded).
        """
        # NOTE: Uncomment below when running with real GEE credentials
        """
        roi = ee.Geometry.Rectangle(self.roi_coords)

        s1 = (ee.ImageCollection(self.S1_COLLECTION)
              .filterBounds(roi)
              .filterDate(self.start_date, self.end_date)
              .filter(ee.Filter.eq('instrumentMode', 'IW'))
              .filter(ee.Filter.listContains('transmitterReceiverPolarisation', self.polarization))
              .select(self.polarization))

        s1_median = s1.median().clip(roi)
        s1_smooth = s1_median.focal_mean(radius=30, kernelType='circle', units='meters')

        flood_mask = s1_smooth.lt(self.threshold_db)

        # Mask permanent water (JRC)
        jrc = ee.Image(self.JRC_WATER).select('seasonality')
        permanent_water = jrc.gte(10)
        flood_only = flood_mask.where(permanent_water, 0)

        return flood_only
        """
        logger.warning("GEE Python API not initialized. Use build_gee_script() for the JS code.")
        return None

    # ──────────────────────────────────────────────────────────────────────────
    def export_to_drive(self, image, description: str):
        """
        Export flood image to Google Drive via GEE batch export.
        Requires GEE Python API to be initialized.
        """
        # NOTE: Uncomment when using with real GEE
        """
        task = ee.batch.Export.image.toDrive(
            image=image.toByte(),
            description=description,
            folder='GeoTwin_Outputs',
            fileNamePrefix=description,
            region=ee.Geometry.Rectangle(self.roi_coords),
            scale=10,
            crs='EPSG:4326',
            maxPixels=1e10
        )
        task.start()
        logger.info(f"Export task started: {description}")
        return task
        """
        logger.warning("GEE not initialized. Export skipped.")
        return None

    # ──────────────────────────────────────────────────────────────────────────
    def save_script(self, filepath: str = "gee_flood_script.js"):
        """Save the GEE JavaScript script to a file for use in Code Editor."""
        script = self.build_gee_script()
        with open(filepath, "w") as f:
            f.write(script)
        logger.info(f"GEE script saved to: {filepath}")
        return script
