"""
================================================================================
  ndvi_monitoring/gee_ndvi.py
  Google Earth Engine — Sentinel-2 NDVI Crop Health Analysis
================================================================================

  USAGE (requires authenticated GEE Python API):
  -----------------------------------------------
    import ee
    from ndvi_monitoring.gee_ndvi import GEENDVIMonitor
    ee.Initialize()

    monitor = GEENDVIMonitor(
        roi_coords=[77.0, 28.0, 78.5, 29.5],   # Delhi-NCR region
        start_date="2024-06-01",
        end_date="2024-08-31",
        max_cloud_pct=20
    )
    ndvi_image = monitor.run_python_api()

================================================================================
"""

import logging
logger = logging.getLogger(__name__)


class GEENDVIMonitor:
    """
    Google Earth Engine based NDVI vegetation health monitor using Sentinel-2.

    Parameters
    ----------
    roi_coords : list of float
        [west, south, east, north] bounding box in decimal degrees.
    start_date : str
        "YYYY-MM-DD"
    end_date : str
        "YYYY-MM-DD"
    max_cloud_pct : int
        Maximum cloud cover percentage to include images (0–100). Default 20.
    low_thresh : float
        NDVI low vegetation threshold. Default 0.2.
    high_thresh : float
        NDVI healthy vegetation threshold. Default 0.5.
    """

    # GEE Collection IDs
    S2_COLLECTION  = "COPERNICUS/S2_SR_HARMONIZED"   # Level-2A surface reflectance
    S2_CLOUD_PROB  = "COPERNICUS/S2_CLOUD_PROBABILITY"

    def __init__(
        self,
        roi_coords: list,
        start_date: str,
        end_date: str,
        max_cloud_pct: int = 20,
        low_thresh: float  = 0.2,
        high_thresh: float = 0.5
    ):
        self.roi_coords   = roi_coords
        self.start_date   = start_date
        self.end_date     = end_date
        self.max_cloud_pct = max_cloud_pct
        self.low_thresh   = low_thresh
        self.high_thresh  = high_thresh

    # ──────────────────────────────────────────────────────────────────────────
    def build_gee_script(self) -> str:
        """Return equivalent GEE JavaScript for use in Code Editor."""
        script = f"""
// ============================================================
//  Sentinel-2 NDVI Crop Health Monitoring — GEE Script
//  Auto-generated by GeoTwin Phase 1
// ============================================================

// 1. Define Region of Interest
var roi = ee.Geometry.Rectangle([{", ".join(map(str, self.roi_coords))}]);

// 2. Cloud masking function using SCL (Scene Classification Layer)
function maskS2Clouds(image) {{
    var scl = image.select('SCL');
    // SCL classes to mask: 3=cloud shadow, 8=cloud med, 9=cloud high, 10=thin cirrus
    var cloudMask = scl.neq(3).and(scl.neq(8)).and(scl.neq(9)).and(scl.neq(10));
    return image.updateMask(cloudMask)
                .divide(10000)           // Scale to [0, 1] reflectance
                .copyProperties(image, ['system:time_start']);
}}

// 3. Load Sentinel-2 SR Harmonized collection
var s2 = ee.ImageCollection('{self.S2_COLLECTION}')
    .filterBounds(roi)
    .filterDate('{self.start_date}', '{self.end_date}')
    .filter(ee.Filter.lt('CLOUDY_PIXEL_PERCENTAGE', {self.max_cloud_pct}))
    .map(maskS2Clouds);

print('Sentinel-2 images after cloud filter:', s2.size());

// 4. Compute NDVI for each image
function addNDVI(image) {{
    var ndvi = image.normalizedDifference(['B8', 'B4']).rename('NDVI');
    return image.addBands(ndvi);
}}
var s2_ndvi = s2.map(addNDVI);

// 5. Median composite (robust to remaining clouds/shadows)
var composite = s2_ndvi.median().clip(roi);
var ndvi_map  = composite.select('NDVI');

// 6. Classify vegetation health
var low_veg  = ndvi_map.lt({self.low_thresh}).rename('Low_Vegetation');
var mod_veg  = ndvi_map.gte({self.low_thresh}).and(ndvi_map.lt({self.high_thresh})).rename('Moderate_Vegetation');
var high_veg = ndvi_map.gte({self.high_thresh}).rename('Healthy_Vegetation');

// Combined classification image (0=low, 1=moderate, 2=healthy)
var classification = ee.Image(0)
    .where(mod_veg,  1)
    .where(high_veg, 2)
    .rename('vegetation_class');

// 7. Visualization palettes
var ndviVis = {{ min: -0.2, max: 0.8, palette: ['d73027','f46d43','fdae61','fee08b','d9ef8b','a6d96a','66bd63','1a9850'] }};
var classVis = {{ min: 0, max: 2, palette: ['ef4444', 'f59e0b', '10b981'] }};

Map.centerObject(roi, 10);
Map.addLayer(ndvi_map,      ndviVis,  'NDVI');
Map.addLayer(classification, classVis, 'Vegetation Classification');
Map.addLayer(composite.select(['B4','B3','B2']).multiply(3.5), {{min:0, max:0.3}}, 'True Color');

// 8. Compute area statistics per class
var class_areas = classification.eq([0, 1, 2])
    .rename(['Low', 'Moderate', 'Healthy'])
    .multiply(ee.Image.pixelArea())
    .reduceRegion({{
        reducer: ee.Reducer.sum(),
        geometry: roi,
        scale: 10,
        maxPixels: 1e10
    }});

print('Vegetation Class Areas (m²):', class_areas);

// 9. Time series chart for NDVI mean
var ts_chart = ui.Chart.image.series({{
    imageCollection: s2_ndvi.select('NDVI'),
    region: roi,
    reducer: ee.Reducer.mean(),
    scale: 100,
    xProperty: 'system:time_start'
}}).setOptions({{
    title: 'NDVI Time Series — Mean',
    vAxis: {{ title: 'NDVI', minValue: -0.2, maxValue: 1.0 }},
    lineWidth: 2,
    colors: ['10b981']
}});
print(ts_chart);

// 10. Export NDVI map to Drive
Export.image.toDrive({{
    image: ndvi_map,
    description: 'ndvi_map_{self.start_date.replace("-","")}_to_{self.end_date.replace("-","")}',
    folder: 'GeoTwin_Outputs',
    fileNamePrefix: 'ndvi_sentinel2',
    region: roi,
    scale: 10,
    crs: 'EPSG:4326',
    maxPixels: 1e10
}});

// Export Classification to Drive
Export.image.toDrive({{
    image: classification.toByte(),
    description: 'ndvi_classification_{self.start_date.replace("-","")}',
    folder: 'GeoTwin_Outputs',
    fileNamePrefix: 'vegetation_classification',
    region: roi,
    scale: 10,
    crs: 'EPSG:4326',
    maxPixels: 1e10
}});
"""
        return script

    # ──────────────────────────────────────────────────────────────────────────
    def run_python_api(self):
        """
        Execute NDVI analysis using the GEE Python API.
        Requires: `import ee; ee.Initialize()` called before.

        Returns
        -------
        dict with 'ndvi' and 'classification' ee.Image objects
        """
        # NOTE: Uncomment when running with real GEE credentials
        """
        roi = ee.Geometry.Rectangle(self.roi_coords)

        def mask_clouds(image):
            scl = image.select('SCL')
            mask = (scl.neq(3).And(scl.neq(8)).And(scl.neq(9)).And(scl.neq(10)))
            return image.updateMask(mask).divide(10000)

        s2 = (ee.ImageCollection(self.S2_COLLECTION)
              .filterBounds(roi)
              .filterDate(self.start_date, self.end_date)
              .filter(ee.Filter.lt('CLOUDY_PIXEL_PERCENTAGE', self.max_cloud_pct))
              .map(mask_clouds))

        composite = s2.median().clip(roi)
        ndvi = composite.normalizedDifference(['B8', 'B4']).rename('NDVI')

        classification = (ee.Image(0)
            .where(ndvi.gte(self.low_thresh).And(ndvi.lt(self.high_thresh)), 1)
            .where(ndvi.gte(self.high_thresh), 2)
            .rename('vegetation_class'))

        return {'ndvi': ndvi, 'classification': classification}
        """
        logger.warning("GEE Python API not initialized. Use build_gee_script() for JS code.")
        return None

    # ──────────────────────────────────────────────────────────────────────────
    def save_script(self, filepath: str = "gee_ndvi_script.js"):
        """Save GEE JavaScript to a .js file."""
        script = self.build_gee_script()
        with open(filepath, "w") as f:
            f.write(script)
        logger.info(f"GEE NDVI script saved: {filepath}")
        return script
